version: '3.8'

services:
  prestashop:
    build: .
    restart: always
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - shop_data:/bitnami/wordpress
    env_file:
      - .env.prestashop
    depends_on:
      - db

  db:
    image: docker.io/mariadb:focal
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env.db

volumes:
  shop_data:
    driver: local
  db_data:
    driver: local
