version: '3.1'

services:

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env.wordpress
    depends_on:
      - db
      - dos-s3sync

  dos-s3sync:
    image: docker.io/grimwm/s3sync:0.2
    restart: always
    volumes:
      - wordpress_data:/mnt
    env_file:
      - .env.s3sync-dos
      - .env.s3sync-dos.creds

  db:
    image: docker.io/mariadb:focal
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env.db

volumes:
  wordpress_data:
    driver: local
  db_data:
    driver: local
