version: '3.8'

services:

  wordpress:
    build: .
    restart: always
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - wp_data:/bitnami/wordpress
    env_file:
      - .env.wordpress
      - .env.wordpress.creds
    depends_on:
      - db
      - dos-s3sync

  s3sync:
    image: docker.io/grimwm/s3sync:0.4
    restart: always
    volumes:
      - wp_data:/mnt
    env_file:
      - .env.s3sync
      - .env.s3sync.creds

  db:
    image: docker.io/mariadb:focal
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env.db

volumes:
  wp_data:
    driver: local
  db_data:
    driver: local
